import requests
from selenium import webdriver
driver = webdriver.Chrome("C:/users/wony5/Desktop/chromedriver_win32/chromedriver.exe")
driver.get('https://comic.naver.com/webtoon/weekday.nhn')

webtitle1 = driver.find_element_by_css_selector('#content > div.list_area.daily_all > div.col.col_selected > div > ul > li:nth-child(1) > a')
print(webtitle1.text)
driver.find_element_by_css_selector('#content > div.list_area.daily_all > div:nth-child(4) > div > ul > li:nth-child(1) > div > a').click()
day1 = driver.find_element_by_css_selector('#content > table > tbody > tr:nth-child(2) > td.num')
print(day1.text)
title1 = driver.find_element_by_css_selector('#content > table > tbody > tr:nth-child(2) > td.title > a')
print(title1.text)
back1 = driver.find_element_by_css_selector('#menu > ul > li.current > a')
back1.click()

webtitle2 = driver.find_element_by_css_selector('#content > div.list_area.daily_all > div:nth-child(4) > div > ul > li:nth-child(2) > a')
print(webtitle2.text)
driver.find_element_by_css_selector('#content > div.list_area.daily_all > div:nth-child(4) > div > ul > li:nth-child(2) > div > a').click()
day2 = driver.find_element_by_css_selector('#content > table > tbody > tr:nth-child(2) > td.num')
print(day2.text)
title2 = driver.find_element_by_css_selector('#content > table > tbody > tr:nth-child(2) > td.title > a')
print(title2.text)
back2 = driver.find_element_by_css_selector('#menu > ul > li.current > a')
back2.click()

webtitle3 = driver.find_element_by_css_selector('#content > div.list_area.daily_all > div:nth-child(3) > div > ul > li:nth-child(2) > a')
print(webtitle3.text)
driver.find_element_by_css_selector("#content > div.list_area.daily_all > div:nth-child(3) > div > ul > li:nth-child(2) > div > a").click()
day3 = driver.find_element_by_css_selector('#content > table > tbody > tr:nth-child(2) > td.num')
print(day3.text)
title3 = driver.find_element_by_css_selector('#content > table > tbody > tr:nth-child(2) > td.title > a')
print(title3.text)
back3 = driver.find_element_by_css_selector('#menu > ul > li.current > a')
back3.click()